name: envvars
on:  [push]
env:
  workflowvar: Good morning
jobs:
  myjob:
    runs-on: ubuntu-latest
    env:
      var: Chytra
    steps:
      - name: PRINT
        run: echo ${{ env.var }}
      - name:  access workflow var
        run: echo ${{ env.workflowvar }}
       
        
  
