name: ouyput vars demp
on:  [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: PRINT
        id: printvar
        run: echo "temp = actions " >> $GITHUB_OUTPUT
      - name:  print the output
        env:
          outputvar: ${{ steps.printvar.outputs.temp }}
        run: echo $outputvar
          
       
        
  
