name: First Workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
       - name: Greeting
         run: echo "Welcome to the World of Github Actions"
       - name: Goodbye
         run: echo "Hope you all had a great time"

